version: 2

models:
  - name: stg_openmeteo_current
    description: "Staging model for OpenMeteo current weather data"
    columns:
      - name: data_source
        description: "The source of the weather data"
        data_tests:
          - accepted_values:
              values: ["openmeteo"]
              quote: false
      - name: date
        description: "The date and time of the weather data"
      - name: extraction_date
        description: "The date and time when the data was extracted"
        datatype: "date"
      - name: state
        description: "The state or region of the location for the weather data"
      - name: district
        description: "The district or locality of the location for the weather data"
      - name: township
        description: "The township or area of the location for the weather data"
      - name: latitude
        description: "The latitude of the location for the weather data"
      - name: longitude
        description: "The longitude of the location for the weather data"
      - name: weather_description
        description: "A textual description of the current weather condition"
      - name: temperature
        description: "The current temperature in degree Celsius"
        unit: "degrees celsius"
      - name: apparent_temperature
        description: "The apparent temperature in degree Celsius"
        unit: "degrees celsius"
      - name: humidity
        description: "The current humidity percentage"
        unit: "percentage"
      - name: wind_speed
        description: "The current wind speed in kilometers per hour"
        unit: "km/h"
      - name: wind_direction
        description: "The wind direction in degrees"
        unit: "degrees"
      - name: wind_gust
        description: "The current wind gust speed in kilometers per hour"
        unit: "km/h"
      - name: precipitation
        description: "The current precipitation in millimeters"
        unit: "mm"
      - name: showers
        description: "The current showers in millimeters"
        unit: "mm"
      - name: snowfall
        description: "The current snowfall in centimeters"
        unit: "cm"
      - name: rain
        description: "The current rain in millimeters"
        unit: "mm"
      - name: cloud_cover
        description: "The current cloud cover percentage"
        unit: "percentage"
      - name: pressure
        description: "The current atmospheric pressure in hectopascals"
        unit: "hPa"
      - name: surface_pressure
        description: "The current surface pressure in hectopascals"
        unit: "hPa"

  - name: stg_openmeteo_forecast
    description: "Staging model for OpenMeteo forecast weather data"
    columns:
      - name: data_source
        description: "The source of the weather data"
        data_tests:
          - accepted_values:
              values: ["openmeteo"]
              quote: false
      - name: date
        description: "The date and time of the weather data"
      - name: extraction_date
        description: "The date and time when the data was extracted "
      - name: state
        description: "The state or region of the location for the weather data"
      - name: district
        description: "The district or locality of the location for the weather data"
      - name: township
        description: "The township or area of the location for the weather data"
      - name: latitude
        description: "The latitude of the location for the weather data"
      - name: longitude
        description: "The longitude of the location for the weather data"
      - name: weather_description
        description: "A textual description of the current weather condition"


  - name: stg_ambientweather_forecast
    description: "Staging model for Ambient Weather forecast data with standardized units"
    columns:
    - name: data_source
      description: "The source of the weather data"
      data_tests:
        - accepted_values:
            values: ["ambient weather"]
            quote: true

    - name: date
      description: "The forecasted date"

    - name: extraction_date
      description: "The date when the data was extracted"

    - name: state
      description: "State or region of the observation"

    - name: district
      description: "District of the observation"

    - name: township
      description: "Township of the observation"

    - name: latitude
      description: "Latitude of the location"

    - name: longitude
      description: "Longitude of the location"

    - name: timezone
      description: "Timezone of the forecasted location"

    - name: weather_summary
      description: "Textual summary of the forecast"

    - name: precipitation_probability
      description: "Probability of precipitation (0–1 scale)"

    - name: precipitation_intensity_mm_per_hr
      description: "Intensity of precipitation in mm/hour (converted from inches/hour × 25.4)"

    - name: precipitation_accumulation_mm
      description: "Total precipitation in millimeters (converted from inches × 25.4)"

    - name: wind_speed_kph
      description: "Wind speed in kilometers per hour (converted from mph × 1.60934)"

    - name: wind_gust_kph
      description: "Wind gust in kilometers per hour (converted from mph × 1.60934)"

    - name: wind_bearing_degrees
      description: "Wind direction in degrees (0–360° from North)"

    - name: temperature_min_celsius
      description: "Minimum temperature in Celsius (converted from Fahrenheit using (°F − 32) × 5/9)"

    - name: temperature_max_celsius
      description: "Maximum temperature in Celsius (converted from Fahrenheit using (°F − 32) × 5/9)"

    - name: weather_icon
      description: "Icon representing the weather conditions visually"
  - name: stg_ambientweather_forecast
    description: "Staging model for Ambient Weather forecast data"
    columns:
      - name: data_source
        description: "The source of the weather data"
        data_tests:
          - accepted_values:
              values: ["ambient weather"]
              quote: true
      - name: date
        description: "The forecasted date"
      - name: extraction_date
        description: "The date when the data was extracted"
      - name: state
        description: "State or region of the observation"
      - name: district
        description: "District of the observation"
      - name: township
        description: "Township of the observation"
      - name: latitude
        description: "Latitude of the location"
      - name: longitude
        description: "Longitude of the location"
      - name: timezone
        description: "Timezone of the forecasted location"
      - name: weather_summary
        description: "Textual summary of the forecast"
      - name: precipitation_probability
        description: "Probability of precipitation"
      - name: precipitation_intensity
        description: "Intensity of precipitation (inches/hour)"
      - name: precipitation_accumulation
        description: "Accumulated precipitation (inches)"
      - name: wind_speed
        description: "Wind speed (mph)"
      - name: weather_icon
        description: "Icon representing the weather"
      - name: wind_bearing
        description: "Wind bearing in degrees"
      - name: wind_gust
        description: "Wind gust (mph)"
      - name: temperature_min
        description: "Minimum forecasted temperature (F)"
      - name: temperature_max
        description: "Maximum forecasted temperature (F)"
