name: Myanmar Weather ETL Pipeline

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/main.yml"
  schedule:
    - cron: "0 1 * * *" ## Trigger on every day at 1:00 UTC | 8:00 AM Thailand

  workflow_dispatch: ## manual trigger

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        source:
          [
            extract_ambient.py,
            extract_meteoblue.py,
            extract_openmeteo.py,
            extract_weatherapi.py,
          ]

    env:
      METEOBLUE_API_KEY: ${{ secrets.METEOBLUE_API_KEY }}
      WEATHER_API_COM_KEY: ${{ secrets.WEATHER_API_COM_KEY }}
      PGHOST: ${{ secrets.PGHOST }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run extract scripts
        run: |
          python ${{ matrix.source }}
