name: Myanmar Weather ETL Pipeline

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/main.yml"
  schedule:
    - cron: "0 21 11 3 *" ## Trigger on May 11 - 9PM (timezone?)

  workflow_dispatch: ## manual trigger

permissions:
  contents: write

jobs:
  simple-etl:
    runs-on: ubuntu-latest
    environment: production
    env:
      meteoblue_api_key: ${{ secrets.meteoblue_api_key }}
      WEATHER_API_COM_KEY: ${{ secrets.WEATHER_API_COM_KEY }}
      PGHOST: ${{ secrets.PGHOST }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Run ETL pipeline
        run: python main.py
