name: Myanmar Weather ELT Pipeline (Transform)

on:
  workflow_run:
    workflows: [Myanmar Weather ELT Pipeline (Extract -> Load)]
    types:
      - completed
  workflow_dispatch: ## manual trigger

permissions:
  contents: write

jobs:
  Transform:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dbt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      - name: Debug dbt models
        run: dbt debug --profiles-dir ./transform --project-dir ./transform

      - name: Run dbt model - ambient_weather
        run: dbt run --profiles-dir ./transform --project-dir ./transform --select stg_ambientweather_forecast

      - name: Run dbt model - meteoblue
        run: dbt run --profiles-dir ./transform --project-dir ./transform --select stg_meteoblue_forecast

      - name: Run dbt model - openmeteo
        run: dbt run --profiles-dir ./transform --project-dir ./transform --select stg_openmeteo_forecast

      - name: Run dbt model - weatherapi
        run: dbt run --profiles-dir ./transform --project-dir ./transform --select stg_weatherapi_forecast

      - name: Run dbt model - all forecasts
        run: dbt run --profiles-dir ./transform --project-dir ./transform --select all_forecasts_unioned

      - name: Run dbt model - all forecasts temperature
        run: dbt run --profiles-dir ./transform --project-dir ./transform --select all_forecasts_temperature
